services:
  - type: web
    name: ubuntu-vps
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: frankfurt
    envVars:
      - key: ROOT_PASS
        value: "2003"
      - key: PORT
        value: "10000"
      - key: BORE_PORT
        value: "48251"
      - key: BORE_SERVER
        value: bore.pub
